# Generated by Django 2.1.3 on 2018-12-13 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('Pass', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(6)])),
                ('AdminFlag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=1000)),
                ('use_day', models.DateField()),
                ('want_go', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MentenanceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('StartDateTime', models.DateField()),
                ('EndDateTime', models.DateField()),
                ('MentenanceOverview', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
