# Generated by Django 2.1.1 on 2018-12-12 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintenance_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('StartDateTime', models.DateField()),
                ('EndDateTime', models.DateField()),
                ('MentenanceOverview', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
