# Generated by Django 2.1.1 on 2018-12-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCMS', '0002_maintenance_master'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee_master',
            new_name='EmployeeMaster',
        ),
        migrations.RenameModel(
            old_name='maintenance_master',
            new_name='MentenanceMaster',
        ),
    ]
